channels:
- conda-forge
dependencies:
- python=3.9.10
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.0
  - dataclasses==0.6
  - mypy-extensions==0.4.3
  - psutil==5.9.2
  - scikit-learn==1.0.2
  - typing-extensions==4.4.0
  - xgboost==1.6.2
name: mlflow-env
